SCR_PlaceableEntitiesRegistry {
 m_sSourceDirectory "{5B01FBD155DC387F}PrefabsEditable/PropItems/Props/Military/AmmoBoxes"
 m_Prefabs {
  "{C8B055BE135BC087}PrefabsEditable/PropItems/Props/Military/AmmoBoxes/E_AmmoBox_556x45_1680rnd_US_TTT.et"
  "{99D8B4513D470A98}PrefabsEditable/PropItems/Props/Military/AmmoBoxes/E_EquipmentBoxWooden_Explosives_TTT.et"
  "{227F37561D6C28DA}PrefabsEditable/PropItems/Props/Military/AmmoBoxes/E_EquipmentBoxWooden_Launcher_US_TTT.et"
  "{9881687C06B40FBD}PrefabsEditable/PropItems/Props/Military/AmmoBoxes/E_EquipmentBoxWooden_Medical_TTT.et"
  "{0DEFE311584EAE1D}PrefabsEditable/PropItems/Props/Military/AmmoBoxes/E_EquipmentBoxWooden_RifleAmmo_US_TTT.et"
 }
}