SCR_MissionHeader {
 World "{B5B476FC3928DFB1}Worlds/TTT_Testworld.ent"
 m_sName "Asset Test"
 m_sAuthor "Rod3ox"
 m_sDescription "Testmission with test map for testing TTT assets"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_bIsSavingEnabled 1
 m_sSaveFileName "TTT_Testmap"
 m_fXpMultiplier 0.1
}